#################################################################
# Generic IP Camera                                             #
# https://www.home-assistant.io/integrations/generic_ip_camera/ #
#################################################################
  
# Weather radar
- platform: generic
  name: San Diego Weather Radar
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?num=1&type=N0R&mapx=400&mapy=240&brand=wui&delay=15&frame=0&scale=1&transx=0&transy=0&severe=0&smooth=1&centerx=400&centery=240&station=NKX&rainsnow=0&lightning=0&noclutter=1&showlabels=1&showstorms=0&rand=26612084